name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Hangi branch'teki değişikliklerde workflow çalışacak

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Pipeline'ın çalışacağı ortam

    steps:
    # 1. Kodları GitHub deposundan çek
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. .NET Core SDK kur
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x  # Kullanılan .NET sürümü

    # 3. Bağımlılıkları yükle
    - name: Restore dependencies
      run: dotnet restore

    # 4. Projeyi derle
    - name: Build
      run: dotnet build --configuration Release

    # 5. Projeyi publish et
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    # 6. Azure Web App'e deploy et
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'Cse415FinalProjectWebeya'  # Azure Web App adını yazın
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish
